spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_SCHEMA_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=true&tinyInt1isBit=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASS}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    resource:
      jwt:
        key-value: test-secretauth
auth:
  test: 1111
  resource-whitelist:
    # swagger相关路径
    - /swagger-ui.html/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /v2/api-docs
    - /v3/api-docs
    - /v3/api-docs/swagger-config
    - /webjars/**
    - /doc.html
    # 认证授权相关路径
    - /oauth/token

