spring:
  profiles:
    active: dev
server:
  port: 8080
mybatis-plus:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    map-underscore-to-camel-case: true
    default-executor-type: reuse
    default-statement-timeout: 25000
    jdbc-type-for-null: null
    use-generated-keys: true
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.junshijun.hub.idea.mapper
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: "null"
      logic-not-delete-value: 0