spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_SCHEMA_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=true&tinyInt1isBit=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASS}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    resource:
      jwt:
        key-value: test-secret
